title: 'Morena Architects'
repository: 'xmamo/maoffice'
timezone: 'Europe/Rome'
permalink: '/:categories/:title'
strict_front_matter: true
theme: null

liquid:
  error_mode: 'strict'
  strict_filters: true

kramdown:
  auto_ids: false

optional_front_matter:
  remove_originals: true
